
on:
  pull_request:

jobs:
  # prep: 
  #   runs-on: ubuntu-latest
  #   outputs:
  #     userId: 234
  #   steps:
  #     - run: echo demo
        
  demo:
    runs-on: ubuntu-latest
    # needs: prep
    steps:
      - run: echo demo
        id: my-step
      - run: |
          echo "${{ github.event.commits[0].message }}"
          echo "${{ toJSON(github.event.pull_request.labels) }}"
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "${{ toJson(github.event.pull_request.labels[0].name) }}"

  
# mkdir -p ./output
# echo "${{ toJSON(github)}}" > ./output/github.json
# echo "${{ toJSON(steps)}}" > ./output/steps.json
# echo "${{ toJSON(needs)}}" > ./output/needs.json
# - uses: actions/upload-artifact@v3
#   with:
#     name: context
#     path: ./output