
on:
  push:

jobs:
  prep: 
    runs-on: ubuntu-latest
    outputs:
      userId: 234
    steps:
      - run: echo demo
        
  demo:
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - run: echo demo
        id: my-step
      - run: |
          mkdir -p ./output
          echo ${{ toJSON(github.event.commits.id)}}}
          echo ${{ toJSON(github.event.commits.author)}}}
      #     echo "${{ toJSON(github)}}" > ./output/github.json
      #     echo "${{ toJSON(steps)}}" > ./output/steps.json
      #     echo "${{ toJSON(needs)}}" > ./output/needs.json
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: context
      #     path: ./output